### ISSUE TITLE
Deleting a policy tries to delete missing file

### ISSUE THREAD

**Issue by shlomizadok** [OpenSCAP/foreman_openscap#33]
```ruby
No such file or directory - /var/lib/foreman/scaptimony/arf/scap1.local.lan/untitled/2014-12-20 00:00:00 UTC/b8a0271cf3c82fdefba13b6d78bebcb1996cae2b27d5e2a59f79b308e91e308f.xml.bz2
Rails.root: /home/szadok/dev/repos/foreman

Application Trace | Framework Trace | Full Trace
/home/szadok/dev/repos/scaptimony/app/models/scaptimony/arf_report.rb:88:in `delete'
/home/szadok/dev/repos/scaptimony/app/models/scaptimony/arf_report.rb:88:in `delete'
```

**Comment by isimluk** [comment]
This will go away once we move ARF reports to the database (#12).

**Comment by isimluk** [comment]
This should never happen again after #12 fix.
